# Automatically label PRs based on changed files

# Agent-specific labels (when agents are working on their respective domains)
'agent: wraith 👻':
  - changed-files:
    - any-glob-to-any-file: ['**/*.scala', 'build.sbt', 'project/**/*']

'agent: mithril ✨':
  - changed-files:
    - any-glob-to-any-file: ['**/*.scala']

'agent: ICE 🧊':
  - changed-files:
    - any-glob-to-any-file: ['**/*.scala', '**/*.md', 'build.sbt']

'agent: eye 👁️':
  - changed-files:
    - any-glob-to-any-file: ['**/test/**/*', '**/*Spec.scala', '**/*Test.scala']

'agent: forge 🔨':
  - changed-files:
    - any-glob-to-any-file: ['src/main/scala/**/vm/**/*', 'src/main/scala/**/consensus/**/*', 'src/main/scala/**/mining/**/*', 'crypto/**/*']

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*', 'README.*']

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['**/Dependencies.scala', 'project/plugins.sbt', 'build.sbt', '**/build.properties']

'docker':
  - changed-files:
    - any-glob-to-any-file: ['docker/**/*', 'Dockerfile*', '.dockerignore']

'ci/cd':
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

'tests':
  - changed-files:
    - any-glob-to-any-file: ['**/test/**/*', '**/*Spec.scala', '**/*Test.scala']

'crypto':
  - changed-files:
    - any-glob-to-any-file: ['crypto/**/*']

'bytes':
  - changed-files:
    - any-glob-to-any-file: ['bytes/**/*']

'rlp':
  - changed-files:
    - any-glob-to-any-file: ['rlp/**/*']

'core':
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']

'configuration':
  - changed-files:
    - any-glob-to-any-file: ['**/*.conf', '**/*.config', '**/*.properties', '.scalafmt.conf', 'scalastyle*.xml']

'build':
  - changed-files:
    - any-glob-to-any-file: ['build.sbt', 'project/**/*']
