FROM ubuntu:xenial

# This "base" image contains the base OS along with some extra programs.

# See the accompanying `build-base.sh` script for tagging details.

ENV DEBIAN_FRONTEND=noninteractive

ADD scripts/install-base-system.sh /root/
RUN /root/install-base-system.sh

ADD scripts/install-nix-common.sh    /home/fukuii/
ADD scripts/install-nix-apps-base.sh /home/fukuii/
RUN chown fukuii:fukuii /home/fukuii/install-*.sh

USER fukuii
WORKDIR /home/fukuii
ENV USER=fukuii

RUN ~/install-nix-apps-base.sh