#!/usr/bin/env sh

dir="$(cd "$(dirname "$0")" && pwd)"

docker volume create fukuii-root
docker volume create mantis-ops-nix # reuse nix volume from mantis-ops
docker run \
  -it \
  --network="host" \
  --rm \
  -e BUILDKITE=true \
  -v=$dir/..:/fukuii \
  -w=/fukuii \
  -v=fukuii-root:/root \
  -v=mantis-ops-nix:/nix \
  -v=$dir/nix.conf:/etc/nix/nix.conf \
  nixpkgs/nix-unstable:latest \
  nix-shell "$@"
